"use client";
import {useEffect,useState} from "react";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Checkbox} from "@/components/ui/checkbox";
import {CalendarDays,Feather,FolderOpen,Sparkles,Plus,ArrowUpRight,Download,Check,LockKeyhole} from "lucide-react";
type Item={id:string;kind:string;title:string;body:string;date:string;done:number;count:number;name:string;size:number};
const localDate=(d=new Date())=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);
export default function Home(){
 const [items,setItems]=useState<Item[]>([]),[view,setView]=useState("plan"),[period,setPeriod]=useState("day"),[day,setDay]=useState(localDate()),[title,setTitle]=useState(""),[body,setBody]=useState(""),[edit,setEdit]=useState<string|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function reload(){const r=await fetch("/api/items");if(!r.ok)throw Error("暂时无法读取内容，请重试。");setItems(await r.json());}
 useEffect(()=>{reload().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 async function request(data:unknown){const r=await fetch("/api/items",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});if(!r.ok)throw Error("储存失败，内容仍保留在这里，请再试一次。");await reload();}
 async function save(e:React.FormEvent){e.preventDefault();if(!title.trim())return;setBusy(true);setError("");try{await request({id:edit,kind:view==="plan"?"task":view,title,body,date:day});setTitle("");setBody("");setEdit(null);setNotice("已储存");}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function change(i:Item){setBusy(true);setError("");try{await request({...i,done:i.kind==="task"?1-i.done:i.done,count:i.kind==="skill"?i.count+1:i.count});setNotice(i.kind==="skill"?"已记录一次练习":"已更新");}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function upload(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;if(f.size>20*1024*1024){setError("请选择 20 MB 以内的档案。");return;}setBusy(true);setError("");try{const data=new FormData();data.append("file",f);const r=await fetch("/api/files",{method:"POST",body:data});if(!r.ok)throw Error("上传失败，请重试。");await reload();setNotice("档案已上传");e.target.value="";}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const start=new Date(day+"T12:00:00");start.setDate(start.getDate()-(start.getDay()+6)%7);const end=new Date(start);end.setDate(end.getDate()+6);
 const tasks=items.filter(i=>i.kind==="task"&&(period==="day"?i.date===day:i.date>=localDate(start)&&i.date<=localDate(end)));
 const done=tasks.filter(i=>i.done).length;
 const beginEdit=(i:Item)=>{setEdit(i.id);setTitle(i.title);setBody(i.body);setDay(i.date||localDate());window.scrollTo({top:0,behavior:"smooth"})};
 const names:{[k:string]:string}={plan:"把今天，留给重要的事。",note:"留下一点，今天的想法。",file:"值得留下的，都在这里。",skill:"把会的事，慢慢练得更好。"};
 return <div className="shell"><header className="topbar"><a className="brand" href="/"><span className="monogram">SJ<span>✦</span></span><span>SIYUAN<span className="brand-sub">PERSONAL SPACE</span></span></a><span className="private"><LockKeyhole size={14}/> 私人空间</span></header>
 <main><Tabs value={view} onValueChange={v=>{setView(v);setTitle("");setBody("");setEdit(null);setNotice("")}}>
 <div className="intro"><div><p className="eyebrow">MY SPACE / 我的日常</p><h1>{names[view]}</h1></div><span className="date-label">{new Date().toLocaleDateString("zh-CN",{year:"numeric",month:"long",day:"numeric",weekday:"long"})}</span></div>
 <TabsList className="main-tabs">{[["plan","日常计划",CalendarDays],["note","随手写写",Feather],["file","档案收藏",FolderOpen],["skill","技能筆记",Sparkles]].map(([v,n,Icon])=><TabsTrigger key={String(v)} value={String(v)}><Icon size={18}/>{String(n)}</TabsTrigger>)}</TabsList>
 {error&&<div role="alert" className="error">{error} <button onClick={()=>reload().then(()=>setError("")).catch(e=>setError(e.message))}>重新读取</button></div>}
 <div role="status" className="status">{busy?"正在储存…":notice}</div>
 <TabsContent value="plan"><div className="plan-grid"><section className="card tasks"><div className="section-heading"><h2>我的待辦 <span className="count">{tasks.length}</span></h2><Tabs value={period} onValueChange={setPeriod}><TabsList><TabsTrigger value="day">每日</TabsTrigger><TabsTrigger value="week">每周</TabsTrigger></TabsList></Tabs></div><div className="date-row"><input aria-label="选择日期" type="date" value={day} onChange={e=>e.target.value&&setDay(e.target.value)}/><span>{period==="week"?localDate(start)+" — "+localDate(end):"一步一步，完成就好。"}</span></div>
 <form onSubmit={save} className="task-form"><input aria-label="待辦事项" value={title} onChange={e=>setTitle(e.target.value)} maxLength={200} placeholder="新增一件想完成的事…" required/><button disabled={busy||loading} className="primary" aria-label="新增待辦"><Plus size={20}/></button></form>
 {loading?<p className="empty">正在读取你的计划…</p>:tasks.length===0?<div className="empty"><CalendarDays size={32}/><h3>还有留白，刚刚好。</h3><p>先写下一件想做的事。</p></div>:<div className="task-list">{tasks.map(i=><div className="task" key={i.id}><Checkbox aria-label={"完成 "+i.title} disabled={busy} checked={!!i.done} onCheckedChange={()=>change(i)}/><span className={i.done?"completed":""}>{i.title}</span><time>{i.date.slice(5)}</time></div>)}</div>}
 <footer className="card-footer">{done} 件已完成 · {tasks.length-done} 件待完成</footer></section>
 <aside><div className="focus-card"><p className="eyebrow">A LITTLE PROGRESS</p><h2>完成一件，<br/>就前进一点。</h2><div className="completion"><strong>{done.toString().padStart(2,"0")}</strong><span>/ {tasks.length.toString().padStart(2,"0")} 件</span></div><div className="meter"><span style={{width:(tasks.length?done/tasks.length*100:0)+"%"}}/></div><p>{period==="day"?"当日":"本周"}完成进度</p></div><button className="quick-link" onClick={()=>setView("note")}><Feather size={22}/><span>脑中有个念头？<small>到随手写写记下来</small></span><ArrowUpRight size={20}/></button></aside></div></TabsContent>
 {["note","skill"].map(kind=><TabsContent key={kind} value={kind}><div className="writing-grid"><section className="card editor"><p className="eyebrow">{kind==="note"?"A PAGE OF YOUR OWN":"LEARN · PRACTICE · SHARE"}</p><h2>{edit?"编辑内容":kind==="note"?"开始写一点吧":"记录一项技能"}</h2><form onSubmit={save}><label>标题<input required maxLength={200} placeholder={kind==="note"?"今天想记住什么？":"例如：剪辑、英文表达、摄影…"} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>{kind==="note"?"内容":"方法、心得与练习目标"}<textarea rows={10} maxLength={50000} placeholder={kind==="note"?"一个想法、一段日常，或还沒整理好的灵感。":"我会做什么？怎么做到？下一次想练习什么？"} value={body} onChange={e=>setBody(e.target.value)}/></label><div className="actions"><button className="primary" disabled={busy||loading}><Check size={16}/>{edit?"储存修改":"储存"+(kind==="note"?"筆记":"技能")}</button>{edit&&<button type="button" onClick={()=>{setEdit(null);setTitle("");setBody("")}}>取消编辑</button>}</div></form></section><section><div className="section-heading"><h2>{kind==="note"?"写过的片段":"我的技能"}</h2><span className="count">{items.filter(i=>i.kind===kind).length}</span></div>{items.filter(i=>i.kind===kind).length===0?<p className="empty">第一篇，从现在开始。</p>:items.filter(i=>i.kind===kind).map(i=><article className="card entry" key={i.id}><p className="eyebrow">{i.date}{kind==="skill"?" · 已练习 "+i.count+" 次":""}</p><h3>{i.title}</h3><p className="note-body">{i.body}</p><div className="actions"><button onClick={()=>beginEdit(i)}>繼续编辑 <ArrowUpRight size={16}/></button>{kind==="skill"&&<button disabled={busy} onClick={()=>change(i)}>＋ 记一次练习</button>}</div></article>)}</section></div></TabsContent>)}
 <TabsContent value="file"><section className="card"><div className="section-heading"><div><h2>我的档案</h2><p className="muted">作品、文件、照片，或下次会用到的素材。</p></div><label className="primary upload"><Plus size={18}/>上传档案<input aria-label="上传档案" disabled={busy||loading} type="file" onChange={upload}/></label></div><p className="muted">单一档案上限 20 MB</p>{items.filter(i=>i.kind==="file").length===0?<div className="empty"><FolderOpen size={36}/><h3>给你的收藏一个位置。</h3><p>上传第一份档案，之后随时回来下载。</p></div>:<div className="files">{items.filter(i=>i.kind==="file").map(i=><a className="file" key={i.id} href={"/api/files?id="+i.id}><FolderOpen size={25}/><span>{i.name}<small>{(i.size/1024/1024).toFixed(2)} MB · {i.date}</small></span><Download size={20}/></a>)}</div>}</section></TabsContent>
 </Tabs><footer className="page-footer"><span>SIYUAN'S SPACE</span><span>日常、想法，和正在成长的自己。</span></footer></main></div>
}
